//generated by ResBuilder in 2022-04-14 09:27:57
#ifndef _RESULT_PIC_INDEX_H_
#define _RESULT_PIC_INDEX_H_

////BmpResID Define Table////

//PAGE 0
#define  PAGE0_4994_03_MENU_ICON_STATE_SEL    0x000001 //  images\03.menu_icon_state_sel.png
#define  PAGE0_4e97_04_MENU_ICON_HEART_SEL    0x000002 //  images\04.menu_icon_heart_sel.png
#define  PAGE0_5dad_05_MENU_ICON_BLOOD_SEL    0x000003 //  images\05.menu_icon_blood_sel.png
#define  PAGE0_daca_COMPASS1                  0x000004 //  images\compass1.png
#define  PAGE0_9d77_HOUR                      0x000005 //  images\hour.png
#define  PAGE0_5fd9_MINUTE_SEC                0x000006 //  images\minute_sec.png

#endif

