//generated by ResBuilder in 2022-04-14 09:18:29
#ifndef _RESULT_STR_INDEX_H_
#define _RESULT_STR_INDEX_H_

////StrResID Define Table////
#define  M26                       1
#define  M27                       2

#endif

